expected-from-site-level-config:
    spark_event_log_enabled: { type: bool(), required: true, use_default: true}
    spark_event_log_dir: { type: str(), required: true, use_default: true}
    spark_driver_memory: { type: str(), required: true, use_default: false}
    spark_executor_memory: { type: str(), required: true, use_default: false}
    spark_yarn_am_memory: { type: str(), required: true, use_default: false}
    spark_history_fs_log_directory: { type: str(), required: true, use_default: false}
    spark_history_fs_update_interval: { type: str(), required: true, use_default: false}
    hdfs_dfs_replication: { type: int(), required: true, use_default: true}
    yarn_app_mapreduce_am_resource_mb: { type: int(), required: true, use_default: true}
    mapreduce_map_memory_mb: { type: int(), required: true, use_default: true}
    mapreduce_reduce_memory_mb: { type: int(), required: true, use_default: true}
    yarn_nodemanager_resource_memory_mb: { type: int(), required: true, use_default: true}
    yarn_scheduler_maximum_allocation_mb: { type: int(), required: true, use_default: true}
    yarn_scheduler_minimum_allocation_mb: { type: int(), required: true, use_default: true}
   